# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'New_graf.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(910, 676)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graf = QtWidgets.QFrame(self.centralwidget)
        self.graf.setMinimumSize(QtCore.QSize(321, 0))
        self.graf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graf.setObjectName("graf")
        self.horizontalLayout.addWidget(self.graf)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(20, 100, 84, 22))
        self.horizontalSlider_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.horizontalSlider_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(20, 60, 84, 22))
        self.horizontalSlider_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.horizontalSlider_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 20, 84, 22))
        self.horizontalSlider.setMaximumSize(QtCore.QSize(200, 16777215))
        self.horizontalSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ones_read = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ones_read.setFont(font)
        self.ones_read.setObjectName("ones_read")
        self.verticalLayout.addWidget(self.ones_read, 0, QtCore.Qt.AlignHCenter)
        self.series_read = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.series_read.setFont(font)
        self.series_read.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.series_read.setObjectName("series_read")
        self.verticalLayout.addWidget(self.series_read, 0, QtCore.Qt.AlignHCenter)
        self.record = QtWidgets.QPushButton(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.record.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.record.setFont(font)
        self.record.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.record.setObjectName("record")
        self.verticalLayout.addWidget(self.record)
        self.open_data = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.open_data.setFont(font)
        self.open_data.setObjectName("open_data")
        self.verticalLayout.addWidget(self.open_data)
        self.create_contour = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.create_contour.setFont(font)
        self.create_contour.setObjectName("create_contour")
        self.verticalLayout.addWidget(self.create_contour)
        self.save_png = QtWidgets.QPushButton(self.groupBox)
        self.save_png.setEnabled(True)
        self.save_png.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.save_png.setFont(font)
        self.save_png.setIconSize(QtCore.QSize(16, 16))
        self.save_png.setObjectName("save_png")
        self.verticalLayout.addWidget(self.save_png)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox1.setObjectName("groupBox1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox1)
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_2.setSpacing(100)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.number_frame = QtWidgets.QLabel(self.groupBox1)
        self.number_frame.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.number_frame.setFont(font)
        self.number_frame.setObjectName("number_frame")
        self.horizontalLayout_2.addWidget(self.number_frame)
        self.number_shot = QtWidgets.QSpinBox(self.groupBox1)
        self.number_shot.setMinimumSize(QtCore.QSize(200, 0))
        self.number_shot.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number_shot.setFont(font)
        self.number_shot.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.number_shot.setMaximum(1000)
        self.number_shot.setObjectName("number_shot")
        self.horizontalLayout_2.addWidget(self.number_shot)
        self.close_app = QtWidgets.QPushButton(self.groupBox1)
        self.close_app.setMinimumSize(QtCore.QSize(200, 0))
        self.close_app.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.close_app.setFont(font)
        self.close_app.setObjectName("close_app")
        self.horizontalLayout_2.addWidget(self.close_app)
        self.verticalLayout_2.addWidget(self.groupBox1)
        self.slider_shot = QtWidgets.QSlider(self.centralwidget)
        self.slider_shot.setOrientation(QtCore.Qt.Horizontal)
        self.slider_shot.setObjectName("slider_shot")
        self.verticalLayout_2.addWidget(self.slider_shot)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 910, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menu)
        self.menu_2.setObjectName("menu_2")
        self.settings = QtWidgets.QMenu(self.menuBar)
        self.settings.setObjectName("settings")
        MainWindow.setMenuBar(self.menuBar)
        self.save_png_menu = QtWidgets.QAction(MainWindow)
        self.save_png_menu.setObjectName("save_png_menu")
        self.open_read_menu = QtWidgets.QAction(MainWindow)
        self.open_read_menu.setObjectName("open_read_menu")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.COM_port = QtWidgets.QAction(MainWindow)
        self.COM_port.setObjectName("COM_port")
        self.legend = QtWidgets.QAction(MainWindow)
        self.legend.setCheckable(True)
        self.legend.setObjectName("legend")
        self.cursor_mouse = QtWidgets.QAction(MainWindow)
        self.cursor_mouse.setCheckable(True)
        self.cursor_mouse.setObjectName("cursor_mouse")
        self.grid = QtWidgets.QAction(MainWindow)
        self.grid.setCheckable(True)
        self.grid.setObjectName("grid")
        self.axis = QtWidgets.QAction(MainWindow)
        self.axis.setCheckable(True)
        self.axis.setObjectName("axis")
        self.speed250000 = QtWidgets.QAction(MainWindow)
        self.speed250000.setCheckable(True)
        self.speed250000.setObjectName("speed250000")
        self.speed115200 = QtWidgets.QAction(MainWindow)
        self.speed115200.setCheckable(True)
        self.speed115200.setChecked(True)
        self.speed115200.setObjectName("speed115200")
        self.speed9600 = QtWidgets.QAction(MainWindow)
        self.speed9600.setCheckable(True)
        self.speed9600.setObjectName("speed9600")
        self.menu_2.addAction(self.speed250000)
        self.menu_2.addAction(self.speed115200)
        self.menu_2.addAction(self.speed9600)
        self.menu.addAction(self.save_png_menu)
        self.menu.addAction(self.open_read_menu)
        self.menu.addAction(self.menu_2.menuAction())
        self.settings.addAction(self.legend)
        self.settings.addAction(self.cursor_mouse)
        self.settings.addAction(self.grid)
        self.settings.addAction(self.axis)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.settings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ones_read.setText(_translate("MainWindow", "Однократно"))
        self.series_read.setText(_translate("MainWindow", "Серия"))
        self.record.setText(_translate("MainWindow", "Запись"))
        self.open_data.setText(_translate("MainWindow", "Открыть"))
        self.create_contour.setText(_translate("MainWindow", "Создать контур"))
        self.save_png.setText(_translate("MainWindow", "Сохранить"))
        self.number_frame.setText(_translate("MainWindow", "Кол-во кадров"))
        self.close_app.setText(_translate("MainWindow", "Закрыть"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Скорость порта"))
        self.settings.setTitle(_translate("MainWindow", "Настройки"))
        self.save_png_menu.setText(_translate("MainWindow", "Сохранить"))
        self.open_read_menu.setText(_translate("MainWindow", "Открыть"))
        self.action1.setText(_translate("MainWindow", "1"))
        self.COM_port.setText(_translate("MainWindow", "COM port"))
        self.legend.setText(_translate("MainWindow", "Легенда"))
        self.cursor_mouse.setText(_translate("MainWindow", "Курсор"))
        self.grid.setText(_translate("MainWindow", "Сетка"))
        self.axis.setText(_translate("MainWindow", "Оси"))
        self.speed250000.setText(_translate("MainWindow", "250000"))
        self.speed115200.setText(_translate("MainWindow", "115200"))
        self.speed9600.setText(_translate("MainWindow", "9600"))

